#!/usr/bin/env python3

import sys
import os
import nltk

from analyzer import Analyzer
from termcolor import colored
from helpers import get_user_timeline

def main():

    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")
    
    user = sys.argv[1].lstrip('@')
    
    tweets = get_user_timeline(user, count = 50)
    if tweets is None:
        print("Error, either the username you entered has a private account or does not exist.")
        sys.exit()
        
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    score = 0
    tokenizer = nltk.tokenize.TweetTokenizer()      

    for tweet in tweets:
        tokens = tokenizer.tokenize(tweet)
        for token in tokens:
            score += analyzer.analyze(token)
        if score > 0.0:
            print(colored(" {} {}".format(score, tweet), "green"))
        elif score < 0.0:
            print(colored(" {} {}".format(score, tweet), "red"))
        else:
            print(colored(" {} {}".format(score, tweet), "yellow"))
        score = 0
    

if __name__ == "__main__":
    main()